// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muzlrtpmiuibwggtkdmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11emxydHBtaXVpYndnZ3RrZG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDczNTgsImV4cCI6MjA2MzY4MzM1OH0.TGIYkty-b4-u6BZMBHTbDy7MKFVmIorBbDX9nWqqQzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);